### ISSUE TITLE
Split the coverage report

### ISSUE THREAD

**Issue by bissolli** [davelosert/vitest-coverage-report-action#160]
Is there any chance we could split the coverage report between the files changed and the whole test suite?

**Comment by davelosert** [comment]
It's not implemented right now, but I'll happily accept a PR that does this.

My first Idea was to have all the changed files come first in the table of files (maybe with a multi-column-span headline), e.g.:

 <table>
      <thead>
        <tr>
         <th align="left">File</th>
         <th align="right">Stmts</th>
         <th align="right">% Branch</th>
         <th align="right">% Funcs</th>
         <th align="right">% Lines</th>
         <th align="left">Uncovered Lines</th>
        </tr>
      </thead>
      <tbody>
        <tr><td colspan="6"><strong>Changed Files</strong></td></tr>
        <tr><td>changedfile.js</td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td>
        <tr><td>changedfile2.js</td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td>
        <tr><td colspan="6"><strong>Unchanged Files</strong></td></tr>
        <tr><td>unchangedfile.js</td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td>
        <tr><td>unchangedfile2.js</td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td>
      <tbody>
<table>

What do you think? Or would you also require the summary only for the changed files?

**Comment by bissolli** [comment]
I would do both, adding the summary for the changed files and a section for these files in the details as suggested.

In my case at least, we are working on a project which has a huge lack of tests and we want to improve it - so ideally every new PR should have a high level of code coverage in the changed files but mainly not drop the overall coverage of the application!

The goal would be to display how well covered is the upcoming code and still give the dev an overview on how is he improving the overall application test coverage.

<h2>Coverage Summary</h2>
<table> 
    <thead> <tr> <th align="center">Status</th> <th align="left">Category</th> <th align="right">Percentage</th> <th align="right">Covered / Total</th> </tr> </thead>
     <tbody> 
        <tr> <td align="left" colspan="4"><b>Changed files</b> (this could be enabled by a configuration flag)</td> </tr> 
        <tr> <td align="center">🟢</td> <td align="left">Lines</td> <td align="right">91.2% / 90%</td> <td align="right">450 / 500</td> </tr> 
        <tr> <td align="center">🟢</td> <td align="left">Statements</td> <td align="right">91.2% / 90%</td> <td align="right">450 / 500</td> </tr> 
        <tr> <td align="center">🟢</td> <td align="left">Functions</td> <td align="right">91.2% / 90%</td> <td align="right">450 / 500</td> </tr> 
        <tr> <td align="center">🟢</td> <td align="left">Branches</td> <td align="right">91.2% / 90%</td> <td align="right">471 / 500</td> </tr> 
        <tr> <td align="left" colspan="4"><b>Overall application</b></td> </tr> 
        <tr> <td align="center">🟢</td> <td align="left">Lines</td> <td align="right">84.66% / 81%</td> <td align="right">1176 / 1389</td> </tr> 
    <tr> <td align="center">🟢</td> <td align="left">Statements</td> <td align="right">84.2% / 80%</td> <td align="right">1194 / 1418</td> </tr> <tr> <td align="center">🟢</td> <td align="left">Functions</td> <td align="right">83.62% / 80%</td> <td align="right">286 / 342</td> </tr> <tr> <td align="center">🟢</td> <td align="left">Branches</td> <td align="right">72.46% / 70%</td> <td align="right">471 / 650</td> </tr>
    </tbody>
 </table>

<details>
    <summary>File Coverage</summary>
    The table you suggested here
</details>

What do you think? 
If you agree I am happy to help! If you have any guide on how to test it, it will be the first time I would be contributing to GH action repo. Should I fork, open a PR in my fork and test the updated action through there?

**Comment by davelosert** [comment]
Hi @bissolli - I still don't have Contribution Guidelines, so I will add these. 😅 

For now it's the usual process:

1. Fork the repository
2. Create a new branch onto where you develop the feature
3. Open up a pull request from the branch of your fork

There are some unit-tests included that you can run with `npm run test` (don't forget to `npm install` before). They are not super sophisticated yet unfortunately. 

To fully test it 'locally', you can also just put up a PR onto your forked repository with your changes, and the action should just execute itself.

If you have any questions feel free to just ask, happy to assist you here! 👍🏻
