### ISSUE TITLE
Default to the same config file names that vitest looks for

### ISSUE THREAD

**Issue by goibon** [davelosert/vitest-coverage-report-action#167]
`vitest` [currently has a list of config file names](https://github.com/vitest-dev/vitest/blob/1fe8286c790cef9063b1f5f8147f6d41fc14bf79/packages/vitest/src/constants.ts#L15-L28) that it supports which include both using both the `vitest*` and `vite*` prefix as well as several file extensions.
However it seems `vitest-coverage-report` only looks for `vite.config.js` unless otherwise specified in the `vite-config-path` option ([default value here](https://github.com/davelosert/vitest-coverage-report-action/blob/5b7a3392ddfaff9c7bb9efe824344ace7906a584/action.yml#L12)).

When looking through existing issues I found #51 in which the author seemed to experience a slight hiccup in regards to having to remember to configure the path because they used a different extension (`ts` instead of `js`), to quote:
> Thanks so much! I was able to successfully test (after remembering I still needed to set Vite config path because we use .ts extension).

This struck me as a very similar experience to the oneI had so I think I'm not alone in subconsciously expecting `vite.config.ts`, `vitest.config.ts` and others to be supported by default.

While not a big issue at all, perhaps it would make for a nicer experience if this action checked for the same list as `vitest` if `vite-config-path` is not specified.
I'll gladly contribute a PR if you think this is an appropriate change 🙂

**Comment by davelosert** [comment]
Hi @goibon ,

thank you very much for the suggestion - that's a great idea and I really like it.

I don't know when I will be able to actually develop this. So if you want to put up a PR to speed up things, I am more than happy to accept that! 🙂
