### ISSUE TITLE
Error when add Summary

### ISSUE THREAD

**Issue by sfer23** [davelosert/vitest-coverage-report-action#190]
![image](https://user-images.githubusercontent.com/3116140/233129207-60bf3c4b-8d62-41e9-8b97-ac13d5653bc0.png)
Report cannot be processed with big amount of files.

Possible solution:
add option to disable File Coverage section in comment.

**Comment by davelosert** [comment]
Hi @sfer23, thank you for reporting this!

Hm, indeed, that's a problem I didn't think of yet. Having that option would be great - do you mind submitting a PR for this?

Mid-Term, this could also be solved (or at least worked around to some degree) by having the coverage-split feature suggested in #160 to only show the file coverage for the files changed in the PR.

**Comment by davelosert** [comment]
I just went ahead and put this in myself. I will have to do a final test tomorrow, but will release it then. 🙂

**Comment by sfer23** [comment]
Nice solution, I'll also try to provide some variant PR, and also will check #160, nice idea also.

**Comment by sfer23** [comment]
Also will test my version and describe the results

**Comment by davelosert** [comment]
@sfer23: I just released the new version 2.0.0 with our changes and the new `file-coverage-mode`-setting. So this should be fixed now! 

Thank you again for the contribution! 🥳
