### ISSUE TITLE
Report does not display on PR

### ISSUE THREAD

**Issue by Wandji69** [davelosert/vitest-coverage-report-action#242]
Using the example on the market place I have implemented something and all the jobs run successfully but the report is not added to the comment section of the PR
The CI file looks like this:

`name: Github-Actions
on:
  push:

jobs:
  test:
    name: running unit tests
    runs-on: ubuntu-latest
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write`

    steps:
    - uses: actions/checkout@v2 
    - name: Install Tools
      run: 
        make install-tools
    - name: Linting
      run:
        make lint
    - name: Running tests Test
      run: 
        make test
    - name: Running Coverage Test 
      run:
        npx vitest --coverage
    - name: Code Coverage Summary Report
      # Also generate the report if tests are failing
      if: always()
      uses: davelosert/vitest-coverage-report-action@v2 
      with: 
        json-summary-path: coverage/coverage-summary.json
        json-final-path: coverage/coverage-final.json
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2 
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
        
Please how do I fix this

**Comment by davelosert** [comment]
Hey @Wandji69 ,
have you checked the action logs to see what went wrong?

Also, you don't need the last step with the `marocchino/sticky-pull-request-comment@v2`. This action will produce the coverage report on it's own and comment it on the pr.

**Comment by Wandji69** [comment]
I was able to fix the issue as I noticed I was triggering the build on:
push. So I made it on: pull_request and it worked perfectly fine now.

Thanks for the support.

**Comment by davelosert** [comment]
Glad to hear! Closing this issue. 🙂
