### ISSUE TITLE
Istanbul reporter required for `json-summary` report

### ISSUE THREAD

**Issue by zirkelc** [davelosert/vitest-coverage-report-action#258]
Since [v0.32.0](https://github.com/vitest-dev/vitest/releases/tag/v0.32.0), Vitest uses the [@vitest/coverage-v8](https://vitest.dev/guide/coverage.html#coverage-providers) provider to collect coverage. This provider seems to generate different reports, for example the `json-summary` report doesn't exist for v8.

In fact, you explicitly have to switch to `istanbul` and add the reporters to generate the `json-summary` and `json` reports:

```sh
npx vitest --coverage.enabled --coverage.provider=istanbul --coverage.reporter=json-summary --coverage.reporter=json
```

Maybe you could add this info to the README to help others.

Thank you for the great package! ❤️

**Comment by davelosert** [comment]
Hi @zirkelc,
thank you for flagging this. I will have a look at it this weekend!

**Comment by davelosert** [comment]
Hi @zirkelc, thanks again for reporting this! ❤️ 

However, from what I understand, `v8` still supports the `json-summary` and, in fact, I am using it with to test this very action since I upgraded to `v0.32.0` without problems. It just has to be explicitly defined, as seen in [my vite.config.ts](https://github.com/davelosert/vitest-coverage-report-action/blob/main/vite.config.js#L7).

How did you come to the conclusion that it wouldn't? Do you have an error in one of your packages with it?

**Comment by zirkelc** [comment]
Sure, I would be happy to contribute to this great project. I will submit a PR in the next few days.

**Comment by zirkelc** [comment]
I had some time and wrote down a few words while the memory is still fresh 😄  

Let me know if it's understandable or if I should add anything else.

**Comment by djdembeck** [comment]
To add to this, I had the default settings for `instanbul`, which do not include `json-summary`.

I had to go from
```typescript
// vite.config.ts
export default defineConfig({
	plugins: [sveltekit()],
	test: {
		coverage: {
			provider: 'istanbul',
		}
	}
})
```
->
```typescript
// vite.config.ts
export default defineConfig({
	plugins: [sveltekit()],
	test: {
		coverage: {
			provider: 'istanbul',
			reporter: ['text', 'json', 'html', 'json-summary']
		}
	}
})

```

**Comment by davelosert** [comment]
@zirkelc : Thank you again very much for this contribution! Really appreciate you taking the time to investigate and write up your findings. 🙂 

The docs are updated and, with the next release, it will also update on the marketplace.
