### ISSUE TITLE
Action is producing warnings of usage of deprecated Node16

### ISSUE THREAD

**Issue by goibon** [davelosert/vitest-coverage-report-action#335]
I noticed that I am getting warnings that I am getting a warning that one of my actions is running using the deprecated Node16 and it specifically links to this this action.

![image](https://github.com/davelosert/vitest-coverage-report-action/assets/2376777/cb66c2c9-d38c-45f0-a366-f7b4d3c26b0e)

I was sure this had already been handled but if I am reading these commits right then it looks like the node runtime of this action was updated in #320 _just after_ releasing v.2.2.0:

![image](https://github.com/davelosert/vitest-coverage-report-action/assets/2376777/6d95d3cc-9f85-4ab7-a30b-a88ae2408ff9)

I am specifying this action as: `uses: davelosert/vitest-coverage-report-action@v2` so I should get any 2.* versions.
If I'm right then I would like to request a release of this action that runs on Node20 and if I'm wrong then I would like to request some assistance 😅

**Comment by davelosert** [comment]
@goibon : I've just released `v2.2.1` - could you check if the warning is gone now? 🙂

**Comment by goibon** [comment]
> @goibon : I've just released `v2.2.1` - could you check if the warning is gone now? 🙂

Awesome, looks like that cleared it. Thanks for the quick response 🥳
