### ISSUE TITLE
Thresholds being ignored 🤔 

### ISSUE THREAD

**Issue by MeanBoyCousin** [davelosert/vitest-coverage-report-action#386]
Hey!

First off, thanks for this tooling, very handy for me right now trying to clean up tech debt.

I've got it set up and reporting to my PRs with the coverage report done between my PR branch and the trunk. However, I only see the blue circles on status.

My `vite.config.ts` setup is as such (omitted unrelated sections):

```ts
test: {
  coverage: {
    all: true,
    reporter: ['lcov', 'json-summary', 'json'],
    thresholds: {
      autoUpdate: true,
      lines: 60,
      branches: 60,
      functions: 60,
      statements: 60,
    },
  },
}
```

Not sure what I'm missing here but hopefully it's something trivial. Thanks in advance!

**Comment by rkhaslarov** [comment]
Hey guys, how to get json summary only for changed files? Like I'm trying to cover only specific type of files, like utils, it's shown in the files coverage, but json summary shows all related tests coverage that were run.

**Comment by rkhaslarov** [comment]
also it would be nice to fail when changed files thresholds are not met

**Comment by rkhaslarov** [comment]
as it was done here https://github.com/davelosert/vitest-coverage-report-action/commit/11ce65308178a23d382492bf8b796e563046c659#diff-83f6d478daa66473de1260296f2d934bcf455a669cc208235d619b511ca52927

**Comment by rkhaslarov** [comment]
@davelosert could you please take a look?

**Comment by MeanBoyCousin** [comment]
@rkhaslarov I'm Happy to help if I can, but you might consider opening your own issue thread as your issues seem unrelated to mine. I suggest providing an MRE, some snippets, or links to your repo (if public) as well if you want help.

**Comment by MeanBoyCousin** [comment]
Well, I feel foolish 🤣 In copying over my workflow config to show you, I realised I was passing the wrong file to the `vite-config-path` parameter of the action. Thanks for the rubber duck!

**Comment by davelosert** [comment]
Haha, no worries, happens. Glad it works now!
